training:
    batch_size: 16
    checkpoint_epochs: 5
    num_epochs: 10
    loss_class: 'DetectionFMCLoss'
    loss_kwargs: {
        'weight': [5, 2, 0]
    }
    optimizer_class: SGD
    optimizer_kwargs: {
        lr: 0.0005,
        weight_decay: 0.001
    }
    scheduler_class: StepLR
    scheduler_kwargs: {
        step_size: 50
    }
data:
    metadata_path: '/Users/williamzhang/Data/coco2017/annotations/instances_val2017.json'
    image_dir: '/Users/williamzhang/Data/coco2017/val2017'
input:
    "image_size": [256, 256]  # row, col
target:
    targ_res: [8, 8]  # row, col
    anchors: [
        [25, 25.0],
        [50, 50.0],
        [100, 100],
        [200, 200]
    ]
    num_classes: 90
arch:
- module: nn
  class: Conv2d
  kwargs:
    in_channels: 3
    out_channels: 32
    kernel_size: 3
    stride: 1
    padding: 1
- module: blocks
  class: ConvBlock
  kwargs:
    in_channels: 32
    out_channels: 32
    kernel_size: 3
    stride: 1
    padding: 1
    groups: 8
  repeat: 2
- module: nn
  class: MaxPool2d
  kwargs:
    kernel_size: 2
    stride: 2
- module: blocks
  class: ConvBlock
  kwargs:
    in_channels: 32
    out_channels: 64
    kernel_size: 3
    stride: 1
    padding: 1
    groups: 8
- module: blocks
  class: ConvBlock
  kwargs:
    in_channels: 64
    out_channels: 64
    kernel_size: 3
    stride: 1
    padding: 1
    groups: 8
- module: nn
  class: MaxPool2d
  kwargs:
    kernel_size: 2
    stride: 2
- module: blocks
  class: ConvBlock
  kwargs:
    in_channels: 64
    out_channels: 96
    kernel_size: 3
    stride: 1
    padding: 1
    groups: 8
- module: blocks
  class: ConvBlock
  kwargs:
    in_channels: 96
    out_channels: 96
    kernel_size: 3
    stride: 1
    padding: 1
    groups: 8
- module: nn
  class: MaxPool2d
  kwargs:
    kernel_size: 2
    stride: 2
- module: blocks
  class: ConvBlock
  kwargs:
    in_channels: 96
    out_channels: 96
    kernel_size: 3
    stride: 1
    padding: 1
    groups: 8
- module: detectors
  class: ConvDetector
  kwargs:
    in_channels: 96
    num_classes: 90
    num_anchors: 4